# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: toto 0.2.3 ruby lib

Gem::Specification.new do |s|
  s.name = "toto".freeze
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["stevepaulo".freeze]
  s.date = "2016-08-04"
  s.description = "Toto, expanded".freeze
  s.email = "stevepaulo@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "Toto.gemspec",
    "VERSION",
    "lib/ext/ext.rb",
    "lib/toto.rb",
    "spec/articles/1900-05-17-the-wonderful-wizard-of-oz.txt",
    "spec/articles/2001-01-01-two-thousand-and-one.txt",
    "spec/articles/2009-04-01-tilt-factor.txt",
    "spec/articles/2009-12-04-some-random-article.txt",
    "spec/articles/2009-12-11-the-dichotomy-of-design.txt",
    "spec/spec_helper.rb",
    "spec/templates/about.rhtml",
    "spec/templates/archives.rhtml",
    "spec/templates/article.rhtml",
    "spec/templates/feed.builder",
    "spec/templates/index.builder",
    "spec/templates/index.rhtml",
    "spec/templates/layout.rhtml",
    "spec/templates/repo.rhtml",
    "spec/templates/tags.rhtml",
    "spec/toto_spec.rb"
  ]
  s.homepage = "http://github.com/stevepaulo/toto".freeze
  s.rubygems_version = "2.6.4".freeze
  s.summary = "Toto, expanded".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rdiscount>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<builder>.freeze, [">= 0"])
      s.add_development_dependency(%q<fuubar>.freeze, [">= 0"])
      s.add_development_dependency(%q<rake>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_development_dependency(%q<gemcutter>.freeze, [">= 0"])
      s.add_development_dependency(%q<pry>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<builder>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<rack>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<rdiscount>.freeze, [">= 0"])
    else
      s.add_dependency(%q<rdiscount>.freeze, [">= 0"])
      s.add_dependency(%q<builder>.freeze, [">= 0"])
      s.add_dependency(%q<fuubar>.freeze, [">= 0"])
      s.add_dependency(%q<rake>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_dependency(%q<gemcutter>.freeze, [">= 0"])
      s.add_dependency(%q<pry>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_dependency(%q<builder>.freeze, [">= 0"])
      s.add_dependency(%q<rack>.freeze, [">= 0"])
      s.add_dependency(%q<rdiscount>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<rdiscount>.freeze, [">= 0"])
    s.add_dependency(%q<builder>.freeze, [">= 0"])
    s.add_dependency(%q<fuubar>.freeze, [">= 0"])
    s.add_dependency(%q<rake>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<gemcutter>.freeze, [">= 0"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
    s.add_dependency(%q<builder>.freeze, [">= 0"])
    s.add_dependency(%q<rack>.freeze, [">= 0"])
    s.add_dependency(%q<rdiscount>.freeze, [">= 0"])
  end
end

